# Pandas dataframe and series
#### powerful data manupulation lib.used for data analysis. Two primary data structures - series and dataframes. series is one dimensional array, dataframe is two dimensional

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
## series
# a panda series is a one dimensional array like object that can hold any data type
# it is similar to a column in a table

import pandas as pd
data= [1,2,3,4,5,6]
series=pd.Series(data)
print('Series \n', series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.Series'>

In [4]:
# create a series from dict 
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data =[10,20,30]
index=['a','b','c']

pd.Series(data, index)

a    10
b    20
c    30
dtype: int64

In [6]:
# DataFrame
# create a dateframe from a dict of list

data={
    'name':['vidit', 'dalmia', 'jack'],
    'age':[25,30,45],
    'City':['banglore', 'new york', 'florida']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     name  age      City
0   vidit   25  banglore
1  dalmia   30  new york
2    jack   45   florida
<class 'pandas.DataFrame'>

In [7]:
# create a dataframe from a list of dict
data=[
    {'name':'vidit', 'age':23,'city': 'delhi'},
    {'name':'john', 'age':53,'city': 'delhi'},
    {'name':'bappy', 'age':23,'city': 'delhi'},
    {'name':'jack', 'age':23,'city': 'delhi'},
]

df = pd.DataFrame(data)
print(df)
print(type(df))

    name  age   city
0  vidit   23  delhi
1   john   53  delhi
2  bappy   23  delhi
3   jack   23  delhi
<class 'pandas.DataFrame'>

In [8]:
df=pd.read_csv('data.csv')
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [9]:
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [10]:
# accessing data from dataframe
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [11]:
df['name']

KeyError: 'name'

In [ ]:
df.loc[0]

name       vidit
age           25
City    banglore
Name: 0, dtype: object

In [ ]:
df.iloc[0]

name       vidit
age           25
City    banglore
Name: 0, dtype: object

In [ ]:
df

     name  age      City
0   vidit   25  banglore
1  dalmia   30  new york
2    jack   45   florida

In [ ]:
# accessing a specified element 
df.at[2,'name']

'jack'

In [ ]:
# accessing specified element using iat
df.iat[2,2]

'florida'

In [ ]:
df

     name  age      City
0   vidit   25  banglore
1  dalmia   30  new york
2    jack   45   florida

In [ ]:
# data manipulation with dataframe

# adding a column
df['salary'] = [50000,15000,17000]
df

     name  age      City  salary
0   vidit   25  banglore   50000
1  dalmia   30  new york   15000
2    jack   45   florida   17000

In [ ]:
# remove a column
df.drop('salary') # it will gice an error beacuse by default it checks in the row index

In [ ]:
df.drop('salary', axis=1) # it is a temporary operation dosent save it

     name  age      City
0   vidit   25  banglore
1  dalmia   30  new york
2    jack   45   florida

In [ ]:
df

     name  age      City  salary
0   vidit   25  banglore   50000
1  dalmia   30  new york   15000
2    jack   45   florida   17000

In [ ]:
# to actually delete the column and save the new table 

df.drop('salary', axis=1, inplace=True)
df

     name  age      City
0   vidit   25  banglore
1  dalmia   30  new york
2    jack   45   florida

In [ ]:
# add age to the column
df['age']=df['age']+1
df

     name  age      City
0   vidit   26  banglore
1  dalmia   31  new york
2    jack   46   florida

In [ ]:
df.drop(0)

     name  age      City
1  dalmia   31  new york
2    jack   46   florida

In [ ]:
df

     name  age      City
0   vidit   26  banglore
1  dalmia   31  new york
2    jack   46   florida

In [ ]:
df.drop(0, inplace=True)

In [ ]:
df

     name  age      City
1  dalmia   31  new york
2    jack   46   florida

In [ ]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 name      str
age     int64
City      str
dtype: object
Statistical summary:
              age
count   2.000000
mean   38.500000
std    10.606602
min    31.000000
25%    34.750000
50%    38.500000
75%    42.250000
max    46.000000

In [ ]:
df.describe()

             age
count   2.000000
mean   38.500000
std    10.606602
min    31.000000
25%    34.750000
50%    38.500000
75%    42.250000
max    46.000000

# Data manipulation and analysis with pandas

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('data.csv')

#fetch the first 5 rows
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [ ]:
# last 5 rows
df.tail(5)

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [ ]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

In [ ]:
## Handling missing values
df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [ ]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
df_filled = df.fillna(0)

In [ ]:
# Filling missing values with the mean of the column
df['sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean()) 
df

          Date Category  Value   Product  Sales Region  sales_fillNA
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [ ]:
df.dtypes

Date                str
Category            str
Value           float64
Product             str
Sales           float64
Region              str
sales_fillNA    float64
dtype: object

In [ ]:
## renaming columns
df=df.rename(columns={'Date':'Sale Date'})
df.head()

    Sale Date Category  Value   Product  Sales Region  sales_fillNA
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [ ]:
#change data types
# df['Value_new'] = df['Value'].astype(int)   -- we can directly use this but sice this coulmn as missing values it will gice us error
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

    Sale Date Category  Value   Product  Sales Region  sales_fillNA  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [ ]:
df['New Value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,sales_fillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [ ]:
# Data aggregating and Grouping
df.head()

,Sale Date,Category,Value,Product,Sales,Region,sales_fillNA,Value_new,New Value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [ ]:
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [ ]:
grouped_sum=df.groupby(['Product','Region'])['Value'].sum()
print(grouped_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [ ]:
# aggregate multiple functions

grouped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
grouped_agg

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [ ]:
### Merging and joining Dataframes
# Create sample DataFrames
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [ ]:
# merge dataframe on the 'ket columns'

pd.merge(df1,df2, on='Key', how='inner')

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [ ]:
pd.merge(df1,df2, on='Key', how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [ ]:
pd.merge(df1,df2, on='Key', how='left')

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [ ]:
pd.merge(df1,df2, on='Key', how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

# Reading data from different sources

In [ ]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df=pd.read_json(StringIO(Data))

In [ ]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [ ]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [ ]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [ ]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [ ]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [ ]:
df.to_csv('wine.csv')

In [13]:
pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------- -------------------------- 1.3/4.0 MB 12.6 MB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 10.7 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1
Note: you may need to restart the kernel to use updated packages.

In [15]:
!pip install html5lib
!pip install beautifulsoup4

Requirement already satisfied: html5lib in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: beautifulsoup4 in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\vidit\Desktop\data-analyst-portfolio\venv\Lib\site-packages (from beautifulsoup4) (4.15.0)

In [16]:

url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url)

In [18]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

In [20]:
url="https://en.wikipedia.org/wiki/Mobile_country_code"
pd.read_html(url,match="Country",header=0)[0]

HTTPError: HTTP Error 403: Forbidden